apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-deployment
  namespace: codesync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing
  template:
    metadata:
      labels:
        app: landing
    spec:
      nodeSelector:
        role: frontend
      containers:
        - name: landing
          image: codesync-landing:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: landing-config
